"""add query permission

Revision ID: dfad075cc2f2
Revises: 89bc7873a3e0
Create Date: 2021-06-28 17:23:52.064017

"""
from alembic import op
import sqlalchemy as sa
from redash.models.types import PseudoJSON


# revision identifiers, used by Alembic.
revision = 'dfad075cc2f2'
down_revision = '89bc7873a3e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_source_groups', sa.Column('query_permission', PseudoJSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_source_groups', 'query_permission')
    # ### end Alembic commands ###
